---
output:
  html_document
always_allow_html: yes
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
library(nomnoml)
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(fig.path = "tools/readme/", dev = "png")

```
# Ecosystem Context for Stock Advice (ECSA)

The goal of the ECSA project is to create bespoke documents containing contextual ecosystem information for managed stocks on the Northeast Continental Shelf. The document creation process relies on the use of survey strata (as defined by the NEFSC [Bottom Trawl Survey](https://www.nefsc.noaa.gov/femad/ecosurvey/mainpage/)) to identify stock areas from which time series of area-averaged ecosystem information can be drawn. For each area of interest, we have automated the aggregation of season-specific time series of ocean temperature and salinity (surface and bottom), zooplankton composition and abundance, and chlorophyll concentration. Each document contains time series of estimated area occupied by a given stock within the specified strata and within the ecosystem as a whole. We also provide estimates for minimum population size (abundance and biomass) based on yearly restratification of habitat given estimates of habitat occupancy. 

## Developing an ECSA project

The document creation process involves three R functions: `create_template.R`, `merge_to_bookdown.R`, and `render_ecsa.R`. The general workflow is as follows:


```{nomnoml nomnoml-decorator}
[<frame>ECSA Workflow|
#fontSize: 7
#spacing: 50
#padding: 20
#stroke: black
#.box: fill=lightblue visual=ellipse
[Final Document (.pdf/.html)] <- [<box>render_ecsa.R ]

[render_ecsa.R ] <- [Reviewed Draft (.Rmd)]

[Reviewed Draft (.Rmd)] <- [<box>merge_to_bookdown.R] 

[merge_to_bookdown.R] <- [Figure skeleton (.Rmd)]

[Reviewed Draft (.Rmd)] <- [<box>merge_to_bookdown.R] 

[merge_to_bookdown.R] <- [Text outline (google doc)]

[Figure skeleton (.Rmd)] -> [Text outline (google doc)]

[Text outline (google doc)] <- [<box>create_template.R]

[Figure skeleton (.Rmd)] <- [create_template.R]

[create_template.R] <- [Stock template (.Rmd)]
]
```


Note: The ECSA is not yet in R package format. Hence, functions must be sourced from the `R/` directory during the document development process. Template `.Rmd` files source the functions by default. 

